classroom/accounts/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'class'
urlpatterns = [
    path('', views.HomeView.as_view(), name='Home'),
    path('signup/', views.SignUpView.as_view(), name='SignUp'),
    path('signup/teacher/', views.TeacherSignUpView.as_view(), name='TeacherSignUp'),
    path('detail/teacher/<int:pk>', views.TeacherDetailView.as_view(), name='detail_teacher'),
    path('update/teacher/<int:pk>', views.TeacherUpdateProfile.as_view(), name='update_teacher'),
    path('signup/student/', views.StudentSignUpView.as_view(), name='StudentSignUp'),
    path('detail/student/<int:pk>', views.StudentDetailView.as_view(), name='detail_student'),
    path('update/student/<int:pk>', views.StudentUpdateProfile.as_view(), name='update_student'),
    path('login/', views.LoginView.as_view(), name='Login'),
    path('logout/', views.LogoutView.as_view(), name='Logout'),
    path('assignment/', views.AssignmentView.as_view(), name='assignment_list'),
    path('assignment/upload/', views.UploadAssignmentView.as_view(), name='upload_assignment'),
    path('assignment/update/<int:pk>', views.UpdateAssignmentView.as_view(), name='update_assignment'),
    path('assignment/delete/<int:pk>', views.DeleteAssignmentView.as_view(), name='delete_assignment'),


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classroom/classroom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='class')),
]

classroom/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import pre_delete
import os

class User(AbstractUser):
    is_teacher = models.BooleanField(default=False)
    is_student = models.BooleanField(default=False)


class Student(models.Model):
    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE, related_name='Student')
    name = models.CharField(max_length=250)
    email = models.EmailField()
    phone = models.CharField(max_length=11)
    roll_no = models.PositiveIntegerField()
    profile_pic = models.ImageField(upload_to='students_pics', blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['roll_no', ]


class Teacher(models.Model):
    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE, related_name='Teacher')
    name = models.CharField(max_length=250)
    email = models.EmailField()
    subject_name = models.CharField(max_length=250)
    phone = models.CharField(max_length=11)
    profile_pic = models.ImageField(upload_to='teachers_pics', blank=True, null=True)
    class_students = models.ManyToManyField(Student, through='StudentInClass')

    def __str__(self):
        return self.name


class StudentMark(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='given_marks')
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='marks')
    subject_name = models.CharField(max_length=250)
    marks_obtained = models.IntegerField()
    mark_max = models.IntegerField()

    def __str__(self):
        return self.subject_name


class StudentInClass(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='class_teacher')
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='class_student_name')

    def __str__(self):
        return self.student.name

    class Meta:
        unique_together = ['student', 'teacher']
        verbose_name_plural = 'StudentInClasses'


class ClassAssignment(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='teacher_assignment')
    student = models.ManyToManyField(Student, related_name='student_assignment')
    created_at = models.DateTimeField(auto_now=True)
    assignment_name = models.CharField(max_length=250)
    assignment = models.FileField(upload_to='assignments')

    def __str__(self):
        return self.assignment_name

    class Meta:
        ordering = ['created_at']


def delete_assignment_file(sender, **kwargs):
    obj = kwargs['instance']
    file_path = ClassAssignment.objects.get(id=obj.id).assignment.path
    if os.path.exists(file_path):
        os.remove(file_path)


pre_delete.connect(receiver=delete_assignment_file, sender=ClassAssignment)


class SubmitAssignment(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='teacher_submit')
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='student_submit')
    created_at = models.DateTimeField(auto_now=True)
    submitted_assignment = models.ForeignKey(ClassAssignment, on_delete=models.CASCADE,
                                             related_name='submission_for_assignment')
    submit = models.FileField(upload_to='submission')

    def __str__(self):
        return 'submitted'+str(self.submitted_assignment.assignment_name)

    class Meta:
        ordering = ['created_at']

classroom/accounts/views.py
from django.shortcuts import render , redirect, get_object_or_404
from .form import StudentForm, TeacherForm, SignupUserForm, TeacherAssignmentForm
from django import views
from .models import ClassAssignment, Teacher, Student, User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin


class HomeView(views.View):
    def get(self, request):
        return render(request, 'index.html')


class SignUpView(views.View):

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('class:Home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, 'accounts/signup.html')


class TeacherSignUpView(views.View):
    view_form = SignupUserForm
    add_view_form = TeacherForm
    template_class = 'accounts/signup_teacher.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('class:Home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, requset):
        return render(requset, self.template_class, {'userform': self.view_form, 'teacherform': self.add_view_form})

    def post(self, request):
        userform = self.view_form(request.POST)
        teacherform = self.add_view_form(request.POST)

        if userform.is_valid() and teacherform.is_valid():
            user = userform.save()
            user.is_teacher = True
            user.save()

            teacher = teacherform.save(commit=False)
            teacher.user = user
            teacher.save()
            return redirect('class:Home')
        return render(request, self.template_class, {'userform': userform, 'teacherform': teacherform})


class StudentSignUpView(views.View):
    view_form = SignupUserForm
    add_view_form = StudentForm
    template_class = 'accounts/signup_student.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('class:Home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, requset):
        return render(requset, self.template_class, {'userform': self.view_form, 'studentform': self.add_view_form})

    def post(self, request):
        userform = self.view_form(request.POST)
        studentform = self.add_view_form(request.POST)

        if userform.is_valid() and studentform.is_valid():
            user = userform.save()
            user.is_teacher = True
            user.save()

            student = studentform.save(commit=False)
            student.user = user
            student.save()
            return redirect('class:Home')
        return render(request, self.template_class, {'userform': userform, 'studentform': studentform})


class LoginView(views.View):
    template_class = 'accounts/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('class:Home')
        return super().dispatch(request, *args, **kwargs)

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_class)

    def post(self, request):
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            messages.success(request, 'wellcome')
            if self.next:
                return redirect(self.next)
            return redirect('class:Home')
        else:
            messages.error(request, 'user not found')
        return render(request, self.template_class)


class LogoutView(LoginRequiredMixin, views.View):

    def get(self, request):
        logout(request)
        messages.success(request, 'you logged out')
        return redirect('class:Home')


class AssignmentView(LoginRequiredMixin, views.View):
    template_class = 'accounts/assignment_list.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_teacher:
            messages.error(request, 'access denied')
            return redirect('class:Home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        assignments = ClassAssignment.objects.filter(teacher=request.user.Teacher)
        return render(request, self.template_class, {'assignments': assignments})


class UploadAssignmentView(LoginRequiredMixin, views.View):
    form_class = TeacherAssignmentForm
    template_class = 'accounts/upload_assignment.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_teacher:
            messages.error(request, 'access denied')
            return redirect('class:Home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_class, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        teacher = request.user.Teacher
        students = teacher.class_students.all()
        if form.is_valid():
            upload = form.save(commit=False)
            upload.teacher = teacher
            upload.save()
            upload.student.add(*students)
            return redirect('class:assignment_list')
        messages.error(request, 'didnt upload')
        return render(request, self.template_class, {'form': form})


class UpdateAssignmentView(LoginRequiredMixin, views.View):
    template_name = 'accounts/update_assignment.html'
    form_class = TeacherAssignmentForm

    def get(self, request, pk):
        assignment = get_object_or_404(ClassAssignment, id=pk)
        form = self.form_class(instance=assignment)
        return render(request, self.template_name, {'form': form})

    def post(self, request, pk):
        assignment = get_object_or_404(ClassAssignment, id=pk)
        form = self.form_class(request.POST, request.FILES, instance=assignment)
        if form.is_valid():
            form.save()
            messages.success(request, 'assignment updated')
            return redirect('class:assignment_list')
        return render(request, self.template_name, {'form': form})


class DeleteAssignmentView(LoginRequiredMixin, views.View):
    template_name = 'accounts/delete_assignment.html'

    def get(self, request, pk):
        obj = get_object_or_404(ClassAssignment, id=pk)
        return render(request, self.template_name, {'object': obj})

    def post(self, request, pk):
        obj = ClassAssignment.objects.filter(id=pk)
        obj.delete()
        messages.success(request, 'deleted')
        return redirect('class:assignment_list')


class TeacherDetailView(LoginRequiredMixin,views.View):
    def dispatch(self, request, *args, **kwargs):
        self.teacher = get_object_or_404(User, id=kwargs['pk']).Teacher
        if request.user.Teacher != self.teacher:
            return redirect('class:Home')
        return super().dispatch(request, *args, **kwargs)


    def get(self, request, pk):
        return render(request, 'accounts/detail_teacher.html', {'teacher': self.teacher})


class StudentDetailView(LoginRequiredMixin,views.View):
    def dispatch(self, request, *args, **kwargs):
        self.student = get_object_or_404(User, id=kwargs['pk']).Student
        if request.user.Student != self.student:
            return redirect('class:Home')
        return super().dispatch(request, *args, **kwargs)


    def get(self, request, pk):
        return render(request, 'accounts/detail_student.html', {'student': self.student})


class TeacherUpdateProfile(LoginRequiredMixin, views.View):
    form_class = TeacherForm
    template_name = 'accounts/update_teacher.html'

    def dispatch(self, request, *args, **kwargs):
        self.teacher = get_object_or_404(User, id=kwargs['pk']).Teacher
        if request.user.Teacher != self.teacher:
            messages.error(request, 'access denied')
            return redirect('class:Home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, pk):
        form = self.form_class(instance=self.teacher)
        return render(request, self.template_name, {'form': form})

    def post(self, request, pk):
        form = self.form_class(request.POST, request.FILES, instance=self.teacher)
        if form.is_valid():
            form.save()
            return redirect('class:detail_teacher', request.user.id)
        return render(request, self.template_name, {'form': form})


class StudentUpdateProfile(LoginRequiredMixin, views.View):
    form_class = StudentForm
    template_name = 'accounts/update_student.html'

    def dispatch(self, request, *args, **kwargs):
        self.student = get_object_or_404(User, id=kwargs['pk']).Student
        if request.user.Student != self.student:
            messages.error(request, 'access denied')
            return redirect('class:Home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, pk):
        form = self.form_class(instance=self.student)
        return render(request, self.template_name, {'form': form})

    def post(self, request, pk):
        form = self.form_class(request.POST, request.FILES, instance=self.student)
        if form.is_valid():
            form.save()
            return redirect('class:detail_student', request.user.id)
        return render(request, self.template_name, {'form': form})

classroom/accounts/templates/accounts/assignment_list.html
{% extends 'base.html' %}
{% block content %}


<div class="container">
  <div class="jumbotron">
{% if assignments.count == 0 %}
  <h2>No Assignments Uploaded Yet</h2>
{% else %}
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Assignment Name</th>
        <th scope="col">Uploaded Date</th>
        <th scope="col">Download</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for assignment in assignments %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ assignment.assignment_name }}</td>
          <td>{{ assignment.created_at }}</td>
          <td><a href="{{ assignment.assignment.url }}" download="{{ assignment.assignment.url }}" class="btn btn-primary">Download</a></td>
          <td><a href="{% url 'class:update_assignment' pk=assignment.id %}" class="btn btn-primary">Update</a></td>
          <td><a href="{% url 'class:delete_assignment' pk=assignment.id %}" class="btn btn-danger">Delete</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endif %}
</div>
</div>
{% endblock %}

classroom/accounts/templates/accounts/delete_assignment.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <div class="jumbotron">
    <h1>Delete {{ object.assignment_name }}?</h1>

    <form method='POST'>
      {% csrf_token %}
      <p>Are you sure you want to remove this Assignment?</p>
      <input class="btn btn-primary" type='submit' value='Yes'>
      <a class="btn btn-danger" href="{% url 'class:assignment_list' %}">Cancel</a>

    </form>
  </div>
</div>
{% endblock %}

classroom/accounts/templates/accounts/detail_student.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="profile">
  <img src="{% static 'images/profile-background-3.PNG' %}" alt="">
  <div class="profile-box">
    {% if student.profile_pic %}
      <img src="{{ student.profile_pic.url }}">
    {% else %}
      <img src="{% static 'images/login-avatar.PNG' %}" alt="">
    {% endif %}
    <div class="profile-details">
      <h1>{{ student.name }}</h1>
      <br>
      <p><i class="far fa-user"></i> Username: {{ student.user.username }}</p>
      <p><i class="fal fa-user-tag"></i> Roll No.: {{ student.roll_no }}</p>
      <p><i class="far fa-phone"></i> Phone: {{ student.phone }}</p>
      <p><i class="far fa-envelope-open-text"></i> Email ID: {{ student.email }}</p>
      <a href="{% url 'class:update_student' pk=user.pk %}"> <p class="edit-button">Edit Profile</p> </a>
    </div>
  </div>
</div>

{% endblock %}

classroom/accounts/templates/accounts/detail_teacher.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="profile">
  <img src="{% static 'images/profile-background-3.PNG' %}" alt="">
  <div class="profile-box">
    {% if teacher.profile_pic %}
    <img src="{{ teacher.profile_pic.url }}" alt="">
    {% else %}
    <img src="{% static 'images/login-avatar.PNG' %}" alt="">
    {% endif %}
    <div class="profile-details">
      <h1>{{ teacher.name }}</h1>
      <br>
      <p><i class="far fa-user"></i> Username: {{ teacher.user.username }}</p>
      <p><i class="fas fa-books"></i> Subject Name: {{ teacher.subject_name }}</p>
      <p><i class="far fa-phone"></i> Phone: {{ teacher.phone }}</p>
      <p><i class="far fa-envelope-open-text"></i> Email ID: {{ teacher.email }}</p>
      <a href="{% url 'class:update_teacher' pk=user.pk %}"><p class="edit-button">Edit profile</p></a>
    </div>
  </div>
</div>
{% endblock %}

classroom/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<div class="login-page">
  <img src="{% static 'images/login-background.PNG' %}" alt="">
  <div class="login-form">
    <div class="avatar">
      <img src="{% static 'images/login-avatar.PNG' %}" alt="">
    </div>
    {% if messages %}
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
      {% for message in messages %}
        <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
      {% endfor %}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %}
    <h1>Login</h1>
    <form action="{% url 'class:Login' %}" method="post">
      {% csrf_token %}
      <p>Username:</p>
      <input type="text" name="username" placeholder="Enter your username">
      <br>
      <br>
      <p>Password:</p>
      <input type="password" name="password" placeholder="Enter password">
      <br>
      <br>
      <input class="btn btn-primary" type="submit" name="" value="Login">
    </form>
    <a href="{% url 'class:SignUp' %}">Don't have an account.</a>
  </div>
</div>


{% endblock %}

classroom/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <div class="login-page">
  <img src="{% static 'images/login-background.PNG' %}" alt="">
    <div class="signup">
      <h1>Sign Up</h1>
      <br>
      <a href="{% url 'class:StudentSignUp' %}"><p>I'm a Student</p> </a>
      <br>
      <a href="{% url 'class:TeacherSignUp' %}"><p>I'm a Teacher</p> </a>
    </div>
    </div>

{% endblock %}

classroom/accounts/templates/accounts/signup_student.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="login-page">
    <img src="{% static 'images/login-background.PNG' %}" alt="">
    <div class="student-signup-form">
      <h3>Fill out the form:</h3>
            <h1>Sign up as a Student.</h1>
      <form method="post" novalidate>
        {% csrf_token %}
        {{ studentform.as_p }}

        <p> <label for="">{{ userform.username.label_tag }}</label>{{ userform.username }}</p>
        <p> {{ userform.username.help_text }}</p>
        <p> <label for="">{{ userform.password1.label_tag }}</label>{{ userform.password1 }}</p>
        <p>Password can't be similar to your other fields and must contain atleast 8 characters.</p>
        <p> <label for="">{{ userform.password2.label_tag }}</label>{{ userform.password2 }}</p>
        <p> {{ userform.password2.help_text }} </p>
        <input type="submit" name="" value="Sign Up">
      </form>
      <a href="{% url 'class:Login' %}">Already have an account.</a>
    </div>
</div>

{% endblock %}

classroom/accounts/templates/accounts/signup_teacher.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="login-page">
    <img src="{% static 'images/login-background.PNG' %}" alt="">
    <div class="student-signup-form">
      <h3>Fill out the form:</h3>
              <h1>Sign up as a Teacher.</h1>
      <form method="post" novalidate>
        {% csrf_token %}
        {{ teacherform.as_p }}

        <p> <label for="">{{ userform.username.label_tag }}</label>{{ userform.username }}</p>
        <p> {{ userform.username.help_text }}</p>
        <p> <label for="">{{ userform.password1.label_tag }}</label>{{ userform.password1 }}</p>
        <p>Password can't be similar to your other fields and must contain atleast 8 characters.</p>
        <p> <label for="">{{ userform.password2.label_tag }}</label>{{ userform.password2 }}</p>
        <p> {{ userform.password2.help_text }} </p>
        <input type="submit" name="" value="Sign Up">
      </form>
      <a href="{% url 'class:Login' %}">Already have an account.</a>
    </div>
</div>

{% endblock %}

classroom/accounts/templates/accounts/update_assignment.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<div class="jumbotron">
  <h1>Update Assignment</h1>
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-danger" name="" value="Update">
  </form>
</div>
</div>
{% endblock %}

classroom/accounts/templates/accounts/update_student.html
{% extends "base.html" %}
{% block content %}


<div class="container">
  <div class="jumbotron">
  <h1>Update Profile</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit" name="" value="Submit">
  </form>
  </div>
  </div>

{% endblock %}

classroom/accounts/templates/accounts/update_teacher.html
{% extends "base.html" %}
{% block content %}


<div class="container">
  <div class="jumbotron">
  <h1>Update Profile</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit" name="" value="Submit">
  </form>
  </div>
  </div>

{% endblock %}

classroom/accounts/templates/accounts/upload_assignment.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<div class="jumbotron">
  <h1>Upload Assignment</h1>
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-danger" name="" value="Upload">
  </form>
</div>
</div>
{% endblock %}