classroom/accounts/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'class'
urlpatterns = [
    path('', views.HomeView.as_view(), name='Home'),
    path('signup/', views.SignUpView.as_view(), name='SignUp'),
    path('signup/teacher/', views.TeacherSignUpView.as_view(), name='TeacherSignUp'),
    path('detail/teacher/<int:pk>', views.TeacherDetailView.as_view(), name='detail_teacher'),
    path('update/teacher/<int:pk>', views.TeacherUpdateProfile.as_view(), name='update_teacher'),
    path('signup/student/', views.StudentSignUpView.as_view(), name='StudentSignUp'),
    path('detail/student/<int:pk>', views.StudentDetailView.as_view(), name='detail_student'),
    path('update/student/<int:pk>', views.StudentUpdateProfile.as_view(), name='update_student'),
    path('login/', views.LoginView.as_view(), name='Login'),
    path('logout/', views.LogoutView.as_view(), name='Logout'),
    path('assignment/', views.AssignmentView.as_view(), name='assignment_list'),
    path('assignment/upload/', views.UploadAssignmentView.as_view(), name='upload_assignment'),
    path('assignment/update/<int:pk>', views.UpdateAssignmentView.as_view(), name='update_assignment'),
    path('assignment/delete/<int:pk>', views.DeleteAssignmentView.as_view(), name='delete_assignment'),


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classroom/classroom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='class')),
]

classroom/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Student manger</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/searchbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/newbase.css' %}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&family=Source+Sans+Pro&display=swap" rel="stylesheet">
  </head>
  <body>

    <nav>
      <div class="toggle">
        <a href="{% url 'class:Home' %}">Class Manager</a>
        <i class="fa fa-bars menu"></i>
      </div>
    </nav>
    <div class="sidebar">
      <ul>
        {% if user.is_authenticated %}
        {% if user.is_teacher%}
          <li> <a href="{% url 'class:upload_assignment' %}">Upload Assignment</a> </li>
          <li> <a href="{% url 'class:assignment_list' %}">Assignment list</a> </li>
          <li> <a href="{% url 'class:detail_teacher' pk=user.pk %}">Profile</a> </li>
          {% else %}
          <li> <a href="{% url 'class:detail_student' pk=user.pk %}">Profile</a> </li>
          {% endif %}
           <li><a class="head-left" href="{% url 'class:Logout' %}">Logout</a></li>

          {% else %}
          <li><a class="head-left" href="{% url 'class:SignUp' %}">Sign Up</a></li>
          <li><a class="head-left" href="{% url 'class:Login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div>

      {% block content %}
      {% endblock %}


      <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
      <script type="text/javascript">
        $(document).ready(function(){
          $('.menu').click(function(){
            $('ul').toggleClass('active');
          })
        })
      </script>

  </body>
</html>

classroom/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% if messages %}
<div class="alert alert-primary alert-dismissible fade show" role="alert">
  {% for message in messages %}
    <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
  {% endfor %}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}

<div class="banner">
      <img src="{% static 'images/first.PNG' %}" alt="">
      <div class="content">
        <h1>Class Manager</h1>
        <p>A Student-Teacher Portal</p>
      </div>
    </div>

    <div class="about">
      <h1>About Us</h1>
      <p>Class Manager is a student-teacher portal with various classroom features like uploading assignments, submissions, Class Notice and many more. Students and Teacher can login in the portal and can experience interactive classroom experience online.
      One of the most powerful features of class manager is its student managing abilities. Teacher can easily manage their students and keep them updated about all of the activities in class.</p>
    </div>

    <div class="use-content">
      <h1>Our Services</h1>
      <div class="row">
        <div class="col-12 col-md-6">
          <div class="box">
            <div class="imgBx">
              <img src="{% static 'images/teacher.PNG' %}" alt="">
            </div>
            <div class="content">
              <h3>For Teacher</h3>
              <ol>
                <li>Teachers can add student in their class through Add Student option.</li>
                <li>After adding students in their class, Teacher can give or edit their class students marks.</li>
                <li>Teachers can also write notice which will be send to all students in their class.</li>
                <li>Teachers can upload assignments through upload assignment options.</li>
                <li>Teacher can check their student's assignment submission and give them marks accordingly.</li>
                <li>Students can message Teachers directly and their messages can be seen in Inbox.</li>
                <li>Teacher can also all the marks given by them to a student by accessing their Marks profile and can edit their marks.</li>
                <li>User can add profile pic through edit profile option.</li>
              </ol>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-6">
          <div class="box">
            <div class="imgBx">
              <img src="{% static 'images/homeimg.PNG' %}" alt="">
            </div>
            <div class="content">
              <h3>For Student</h3>
              <ol>
                <li>Students can login in the portal and keep themselves updated of all the activities going on in the class.</li>
                <li>Students can see the notice given by their teacher in the Class Notice option.</li>
                <li>Students can download their assignments in the Assignments option and can also submit it their. ( Once assignment is submitted, it can't be changed later. )</li>
                <li> Students can contact any teacher through message option in All Teachers List. </li>
                <li>Students can check their marks in the Marks option.</li>
                <li>User can add profile pic through edit profile option.</li>
              </ol>
          </div>
        </div>
      </div>
    </div>
    </div>

    <div class="research">
      <div class="row">
        <div class="col-md-4">
          <img src="{% static 'images/mastery-based-education.PNG' %}" alt="">
        </div>
        <div class="col-md-8">
          <div class="digital-content">
            <h2>Digital Learning</h2>
            <br>
            <p>We surveyed over 16,000 teachers and administrators to better understand the state of digital learning. Class Manager provides all facilities that is needed for improvising digital learning.</p>
          </div>
        </div>
      </div>
    </div>

    <div class="social">
      <h1>Are you ready to advance what's possible in education.</h1>
      <h3>Then connect with us on social media.</h3>
      <a class="social-icon" href="#"><i class="fab fa-facebook-f"></i></a>
      <a class="social-icon" href="#"><i class="fab fa-twitter"></i></a>
      <a class="social-icon" href="#"><i class="fab fa-instagram"></i></a>
      <a class="social-icon" href="#"><i class="fab fa-google"></i></a>
      <a class="social-icon" href="#"><i class="fab fa-linkedin-in"></i></a>
    </div>

{% endblock %}